all:
  vars:
    ansible_user: debian
    snapshots_branch: main
    versions_branch: main
  children:
    production:
      children:
        services-all:
          hosts:
            51.89.227.206:
        services-dating:
          hosts:
            vps-99ae1d89.vps.ovh.net:
