all:
  vars:
    ansible_user: debian
    snapshots_branch: main
    versions_branch: main
  children:
    production:
      children:
        services_all:
          hosts:
            51.89.227.206:
              services_directory: ota-services-all
              services_repository: https://github.com/OpenTermsArchive/services-all.git
              snapshots_directory: ota-snapshots
              snapshots_repository: git@github.com:ambanum/OpenTermsArchive-snapshots.git
              snapshots_branch: master
              versions_directory: ota-versions
              versions_repository: git@github.com:ambanum/OpenTermsArchive-versions.git
              versions_branch: master
        dating:
          hosts:
            vps-99ae1d89.vps.ovh.net:
              services_directory: ota-services-dating
              services_repository: https://github.com/OpenTermsArchive/services-dating.git
              snapshots_directory: ota-snapshots-dating
              snapshots_repository: git@github.com:OpenTermsArchive/snapshots-dating.git
              versions_directory: ota-versions-dating
              versions_repository: git@github.com:OpenTermsArchive/versions-dating.git
        france:
          hosts:
            198.244.142.9:
              services_directory: ota-services-france
              services_repository: https://github.com/OpenTermsArchive/declarations-france.git
              snapshots_directory: ota-snapshots-france
              snapshots_repository: git@github.com:OpenTermsArchive/snapshots-france.git
              versions_directory: ota-versions-france
              versions_repository: git@github.com:OpenTermsArchive/versions-france.git
