all:
  vars:
    ansible_user: debian
    snapshots_branch: main
    versions_branch: main
  children:
    production:
      children:
        services-all:
          hosts:
            51.89.227.206:
              services_directory: ota-services-all
              services_repository: https://github.com/OpenTermsArchive/services-all.git
              snapshots_directory: ota-snapshots
              snapshots_repository: git@github.com:ambanum/OpenTermsArchive-snapshots.git
              snapshots_branch: master
              versions_directory: ota-versions
              versions_repository: git@github.com:ambanum/OpenTermsArchive-versions.git
              versions_branch: master
        services-dating:
          hosts:
            vps-99ae1d89.vps.ovh.net:
              services_directory: ota-services-dating
              services_repository: https://github.com/OpenTermsArchive/services-dating.git
              snapshots_directory: ota-snapshots-dating
              snapshots_repository: git@github.com:OpenTermsArchive/snapshots-dating.git
              versions_directory: ota-versions-dating
              versions_repository: git@github.com:OpenTermsArchive/versions-dating.git
