- name: Install GitHub CLI
  ansible.builtin.shell: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    sudo apt update
    sudo apt install gh
  tags:
    - setup

- name: Ensure /home/{{ ansible_user }}/.config/gh/ dir exists
  file:
    path: '/home/{{ ansible_user }}/.config/gh/'
    state: directory
  tags:
    - setup

- name: Add GitHub CLI Config
  copy:
    src: gh-host.yml
    dest: '/home/{{ ansible_user }}/.config/gh/hosts.yml'
  tags:
    - setup
