name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: "ambanum/OpenTermsArchive/.github/workflows/test.yml@main"

  get_instances:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Set matrix with instance names
        id: get_instance_names
        uses: mikefarah/yq@master
        with:
          cmd: yq ".all.children.production.children | keys" ops/inventories/production.yml -o=json | tr '\n' ' '
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"instance\":${{ toJson(steps.get_instance_names.outputs.result) }}}"

  deploy:
    needs: [ test, get_instances ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # deploy other instances even if one fails to deploy
      matrix: ${{ fromJSON(needs.get_instances.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Get target server hostname
        id: get_hostname
        uses: mikefarah/yq@master
        with:
          cmd: yq ".all.children.production.children.${{ matrix.instance }}.hosts.* | key" ops/inventories/production.yml
      - name: Get target server fingerprint
        id: get_fingerprint
        uses: mikefarah/yq@master
        with:
          cmd: yq '.all.children.production.children.${{ matrix.instance }}.hosts.["${{ steps.get_hostname.outputs.result }}"].ed25519_fingerprint' ops/inventories/production.yml
      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ steps.get_hostname.outputs.result }} ssh-ed25519 ${{ steps.get_fingerprint.outputs.result }}
      - run: echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > vault.key
      - run: pip install --upgrade setuptools
      - run: pip install 'ansible ~= 2.9'
      - run: ansible-playbook ops/site.yml --inventory ops/inventories/production.yml --limit ${{ matrix.instance }}
