name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: "ambanum/OpenTermsArchive/.github/workflows/test.yml@main"
  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - contrib
          - dating
          - france
          - france_elections
          - pga
          - p2b_compliance

    steps:
      - uses: actions/checkout@v2
      - name: Get target server hostname
        id: get_hostname
        uses: mikefarah/yq@master
        with:
          cmd: yq ".all.children.production.children.${{ matrix.instance }}.hosts.* | key" ops/inventories/production.yml
      - name: Get target server fingerprint
        id: get_fingerprint
        uses: mikefarah/yq@master
        with:
          cmd: yq .all.children.production.children.${{ matrix.instance }}.hosts.${{ steps.get_hostname.outputs.result }}.ed25519_fingerprint ops/inventories/production.yml
      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ steps.get_hostname.outputs.result }} ssh-ed25519 ${{ steps.get_fingerprint.outputs.result }}
      - run: echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > vault.key
      - run: pip install --upgrade setuptools
      - run: pip install 'ansible ~= 2.9'
      - run: ansible-playbook ops/site.yml --inventory ops/inventories/production.yml --limit ${{ matrix.instance }}
