name: Test

on:
  push:
    branches-ignore:
      - master # tests will be launched by workflow_callpush:
  pull_request:
    types: [opened, reopened]
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        operating_system: [ubuntu-latest, windows-2019]
      fail-fast: false # run tests on other operating systems even if one fails

    runs-on: ${{ matrix.operating_system }}

    steps:
      - run: |
          git config --global user.name 'OTA Bot'
          git config --global user.email 'bot@opentermsarchive.org'
          git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run validate:schema
      - run: npm test
