name: Test

on:
  push:
    branches-ignore:
      - main # tests will be launched by workflow_call push:
  pull_request:
    types: [ opened, reopened ]
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        operating_system: [ ubuntu-latest, windows-latest ]
      fail-fast: false # run tests on other operating systems even if one fails

    runs-on: ${{ matrix.operating_system }}

    steps:
      - run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Start MongoDB (UNIX)
        if: runner.os != 'Windows'
        run: |
          mkdir /tmp/test-database
          mongod --dbpath /tmp/test-database --fork --logpath /tmp/mongodb-log
      - name: Start MongoDB (Windows)
        if: runner.os == 'Windows'
        run: |
          Set-Service MongoDB -StartupType Automatic          
          Start-Service -Name MongoDB
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  validate_declarations:
    strategy:
      matrix:
        operating_system: [ ubuntu-latest, windows-latest ]
      fail-fast: false # run tests on other operating systems even if one fails

    runs-on: ${{ matrix.operating_system }}

    steps:
      - run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: OpenTermsArchive/contrib-declarations
          path: ./contrib-declarations
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: cd ./contrib-declarations && npm install
      - run: npm ci
      - run: ./node_modules/.bin/cross-env NODE_ENV=ci npm run declarations:validate:schema
